export default {
  page: 1,
  results: [
    {
      adult: false,
      gender: 2,
      id: 287,
      known_for: [
        {
          adult: false,
          backdrop_path: "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
          genre_ids: [18],
          id: 550,
          media_type: "movie",
          original_language: "en",
          original_title: "Fight Club",
          overview:
            'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
          poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
          release_date: "1999-10-15",
          title: "Fight Club",
          video: false,
          vote_average: 8.4,
          vote_count: 24270,
        },
        {
          adult: false,
          backdrop_path: "/yVPcPk96E6Qffiyez2oJc7OKD2A.jpg",
          genre_ids: [18, 28, 53, 10752],
          id: 16869,
          media_type: "movie",
          original_language: "en",
          original_title: "Inglourious Basterds",
          overview:
            'In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as "The Basterds" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis. The Basterds, lead by Lt. Aldo Raine soon cross paths with a French-Jewish teenage girl who runs a movie theater in Paris which is targeted by the soldiers.',
          poster_path: "/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
          release_date: "2009-08-19",
          title: "Inglourious Basterds",
          video: false,
          vote_average: 8.2,
          vote_count: 18804,
        },
        {
          adult: false,
          backdrop_path: "/dYjZ27hDw2QFaEIfzbNGwW0IkV9.jpg",
          genre_ids: [80, 9648, 53],
          id: 807,
          media_type: "movie",
          original_language: "en",
          original_title: "Se7en",
          overview:
            'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
          poster_path: "/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
          release_date: "1995-09-22",
          title: "Se7en",
          video: false,
          vote_average: 8.4,
          vote_count: 17201,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Pitt",
      popularity: 34.793,
      profile_path: "/oTB9vGIBacH5aQNS0pUM74QSWuf.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 1370,
      known_for: [
        {
          adult: false,
          backdrop_path: "/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg",
          genre_ids: [12, 14, 28],
          id: 122,
          media_type: "movie",
          original_language: "en",
          original_title: "The Lord of the Rings: The Return of the King",
          overview:
            "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
          poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
          release_date: "2003-12-01",
          title: "The Lord of the Rings: The Return of the King",
          video: false,
          vote_average: 8.5,
          vote_count: 19683,
        },
        {
          adult: false,
          backdrop_path: "/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg",
          genre_ids: [12, 14, 28],
          id: 121,
          media_type: "movie",
          original_language: "en",
          original_title: "The Lord of the Rings: The Two Towers",
          overview:
            "Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
          poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
          release_date: "2002-12-18",
          title: "The Lord of the Rings: The Two Towers",
          video: false,
          vote_average: 8.4,
          vote_count: 18240,
        },
        {
          adult: false,
          backdrop_path: "/1uHTJcL7fCxulnmK2fzUAIOvOHm.jpg",
          genre_ids: [18],
          id: 510,
          media_type: "movie",
          original_language: "en",
          original_title: "One Flew Over the Cuckoo's Nest",
          overview:
            "While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy, inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.",
          poster_path: "/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
          release_date: "1975-11-18",
          title: "One Flew Over the Cuckoo's Nest",
          video: false,
          vote_average: 8.4,
          vote_count: 8640,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Dourif",
      popularity: 18.234,
      profile_path: "/z2LYR7Ickql7g5hnWJSIAWMPD4o.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 18,
      known_for: [
        {
          adult: false,
          backdrop_path: "/bvpI11RJbE6lHSWCrhvNC1S1MtO.jpg",
          genre_ids: [16, 10751],
          id: 12,
          media_type: "movie",
          original_language: "en",
          original_title: "Finding Nemo",
          overview:
            "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
          poster_path: "/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
          release_date: "2003-05-30",
          title: "Finding Nemo",
          video: false,
          vote_average: 7.8,
          vote_count: 16483,
        },
        {
          adult: false,
          backdrop_path: "/xgDj56UWyeWQcxQ44f5A3RTWuSs.jpg",
          genre_ids: [16, 35, 10751, 14],
          id: 2062,
          media_type: "movie",
          original_language: "en",
          original_title: "Ratatouille",
          overview:
            "Remy, a resident of Paris, appreciates good food and has quite a sophisticated palate. He would love to become a chef so he can create and enjoy culinary masterpieces to his heart's delight. The only problem is, Remy is a rat. When he winds up in the sewer beneath one of Paris' finest restaurants, the rodent gourmet finds himself ideally placed to realize his dream.",
          poster_path: "/npHNjldbeTHdKKw28bJKs7lzqzj.jpg",
          release_date: "2007-06-28",
          title: "Ratatouille",
          video: false,
          vote_average: 7.8,
          vote_count: 14035,
        },
        {
          adult: false,
          backdrop_path: "/o11rDwFa7nZMVI57Mm3C44YwmmF.jpg",
          genre_ids: [12, 16, 35, 10751],
          id: 127380,
          media_type: "movie",
          original_language: "en",
          original_title: "Finding Dory",
          overview:
            "Dory is reunited with her friends Nemo and Marlin in the search for answers about her past. What can she remember? Who are her parents? And where did she learn to speak Whale?",
          poster_path: "/3UVe8NL1E2ZdUZ9EDlKGJY5UzE.jpg",
          release_date: "2016-06-16",
          title: "Finding Dory",
          video: false,
          vote_average: 7,
          vote_count: 10647,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Garrett",
      popularity: 13.647,
      profile_path: "/813ffbpoaoaJRdoe1yrbivboWKp.jpg",
    },
    {
      adult: false,
      backdrop_path: "/eRfANc4xSRNaR8E9fUI9hdLkCWB.jpg",
      genre_ids: [35, 18],
      id: 425980,
      media_type: "movie",
      original_language: "en",
      original_title: "Brad's Status",
      overview:
        "Although Brad has a satisfying career, a sweet wife and a comfortable life in suburban Sacramento, things aren't quite what he imagined during his college glory days. When he accompanies his musical prodigy son on a university tour, he can't help comparing his life with those of his four best college friends who seemingly have more wealthy and glamorous lives. But when circumstances force him to reconnect with his former friends, Brad begins to question whether he has really failed or if their lives are actually more flawed than they appear.",
      popularity: 8.026,
      poster_path: "/uXiNpvig7EMq18VyNBUTlWrmN0q.jpg",
      release_date: "2017-09-14",
      title: "Brad's Status",
      video: false,
      vote_average: 6.2,
      vote_count: 306,
    },
    {
      adult: false,
      gender: 2,
      id: 69010,
      known_for: [
        {
          adult: false,
          backdrop_path: "/7lsnS82c1RXklfZUpLxiVd2HdR1.jpg",
          genre_ids: [18, 80],
          id: 11327,
          media_type: "movie",
          original_language: "en",
          original_title: "Midnight Express",
          overview:
            'Billy Hayes is caught attempting to smuggle drugs out of Turkey. The Turkish courts decide to make an example of him, sentencing him to more than 30 years in prison. Hayes has two opportunities for release: the appeals made by his lawyer, his family, and the American government, or the "Midnight Express".',
          poster_path: "/mW54BtqVRxrPnoO9gQQjTLJlnuU.jpg",
          release_date: "1978-08-31",
          title: "Midnight Express",
          video: false,
          vote_average: 7.6,
          vote_count: 1307,
        },
        {
          adult: false,
          backdrop_path: "/qgPYU8xDYiZPKapK0sOvfIEKRtH.jpg",
          genre_ids: [18, 36],
          id: 9443,
          media_type: "movie",
          original_language: "en",
          original_title: "Chariots of Fire",
          overview:
            "In the class-obsessed and religiously divided UK of the early 1920s, two determined young runners train for the 1924 Paris Olympics. Eric Liddell, a devout Christian born to Scottish missionaries in China, sees running as part of his worship of God's glory and refuses to train or compete on the Sabbath. Harold Abrahams overcomes anti-Semitism and class bias, but neglects his beloved sweetheart in his single-minded quest.",
          poster_path: "/ddUsckTbI2xmuaTRMG2SivmQcRY.jpg",
          release_date: "1981-05-15",
          title: "Chariots of Fire",
          video: false,
          vote_average: 6.9,
          vote_count: 672,
        },
        {
          adult: false,
          backdrop_path: "/tKyxF6ZyxF65CcJKBKId1VavpGP.jpg",
          genre_ids: [35, 9648, 18, 80],
          id: 10403,
          media_type: "movie",
          original_language: "en",
          original_title: "The Player",
          overview:
            "A Hollywood studio executive is being sent death threats by a writer whose script he rejected - but which one?",
          poster_path: "/p4ys4a4yASjKuWzsNWY1B7xP5kZ.jpg",
          release_date: "1992-04-03",
          title: "The Player",
          video: false,
          vote_average: 7.2,
          vote_count: 585,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Davis",
      popularity: 11.849,
      profile_path: "/2c4tlWIBJcOizIqShTVHDXeuawb.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 7087,
      known_for: [
        {
          adult: false,
          backdrop_path: "/lxwzY9vNwjDgxWKt3zZ6zcU6rEJ.jpg",
          genre_ids: [28, 12, 16, 10751],
          id: 9806,
          media_type: "movie",
          original_language: "en",
          original_title: "The Incredibles",
          overview:
            "Bob Parr has given up his superhero days to log in time as an insurance adjuster and raise his three children with his formerly heroic wife in suburbia. But when he receives a mysterious assignment, it's time to get back into costume.",
          poster_path: "/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
          release_date: "2004-10-27",
          title: "The Incredibles",
          video: false,
          vote_average: 7.7,
          vote_count: 15272,
        },
        {
          adult: false,
          backdrop_path: "/xgDj56UWyeWQcxQ44f5A3RTWuSs.jpg",
          genre_ids: [16, 35, 10751, 14],
          id: 2062,
          media_type: "movie",
          original_language: "en",
          original_title: "Ratatouille",
          overview:
            "Remy, a resident of Paris, appreciates good food and has quite a sophisticated palate. He would love to become a chef so he can create and enjoy culinary masterpieces to his heart's delight. The only problem is, Remy is a rat. When he winds up in the sewer beneath one of Paris' finest restaurants, the rodent gourmet finds himself ideally placed to realize his dream.",
          poster_path: "/npHNjldbeTHdKKw28bJKs7lzqzj.jpg",
          release_date: "2007-06-28",
          title: "Ratatouille",
          video: false,
          vote_average: 7.8,
          vote_count: 14037,
        },
        {
          adult: false,
          backdrop_path: "/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg",
          genre_ids: [28, 12, 16, 10751],
          id: 260513,
          media_type: "movie",
          original_language: "en",
          original_title: "Incredibles 2",
          overview:
            "Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.",
          poster_path: "/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg",
          release_date: "2018-06-14",
          title: "Incredibles 2",
          video: false,
          vote_average: 7.5,
          vote_count: 11035,
        },
      ],
      known_for_department: "Directing",
      media_type: "person",
      name: "Brad Bird",
      popularity: 9.508,
      profile_path: "/ZX1hAfWK1zslpB6ifwgDP2uBqn.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 36067,
      known_for: [
        {
          backdrop_path: "/cvlLBcQWpO9X21jDHhgPJnE2aVq.jpg",
          first_air_date: "2000-10-06",
          genre_ids: [80, 18, 9648],
          id: 1431,
          media_type: "tv",
          name: "CSI: Crime Scene Investigation",
          origin_country: ["US"],
          original_language: "en",
          original_name: "CSI: Crime Scene Investigation",
          overview:
            "A Las Vegas team of forensic investigators are trained to solve criminal cases by scouring the crime scene, collecting irrefutable evidence and finding the missing pieces that solve the mystery.",
          poster_path: "/9XecVOLLkbGBNnpF2PvP8vQBmww.jpg",
          vote_average: 7.7,
          vote_count: 860,
        },
        {
          adult: false,
          backdrop_path: "/iYCQyL7kmVkjALcodcbo48z0bJD.jpg",
          genre_ids: [14, 10749],
          id: 11352,
          media_type: "movie",
          original_language: "en",
          original_title: "Always",
          overview:
            "Pete Sandich is a reckless fire-fighting pilot who is killed in what was to have been his final mission. Ascending to Heaven, Pete is introduced to business-like angel who instructs the spectral Pete to pass on his aviation knowledge to his young successor. While doing so, Pete also smoothes the course of romance for his earthly girlfriend who, after several months of grieving, finally falls in love with another man.",
          poster_path: "/igKxOqpwf0cKHhJ07TS8OMXLtyl.jpg",
          release_date: "1989-12-22",
          title: "Always",
          video: false,
          vote_average: 6.3,
          vote_count: 455,
        },
        {
          backdrop_path: "/e3n5q7RB47R8px3EN1ZXhC5kyLq.jpg",
          first_air_date: "1995-03-26",
          genre_ids: [18, 10765],
          id: 21561,
          media_type: "tv",
          name: "The Outer Limits",
          origin_country: ["US"],
          original_language: "en",
          original_name: "The Outer Limits",
          overview:
            "Anthology series of composed of distinct story episodes, sometimes with a plot twist at the end, with occasional recurring story elements that were often tied together during season-finale clip shows.",
          poster_path: "/w3jTh6DeBO3B7uTKsnQXDc29QfJ.jpg",
          vote_average: 7.9,
          vote_count: 137,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Johnson",
      popularity: 9.559,
      profile_path: "/jw7MmA6mCMAQUivF7NDCoVmBbCe.jpg",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 399798,
      media_type: "movie",
      original_language: "en",
      original_title: "Brad Williams: Fun Size",
      overview:
        "Comedian Brad Williams' standup topics include his experiences as a little person and how to please your woman in bed.",
      popularity: 2.06,
      poster_path: "/rYmWwVII6JMnJMxJXHyXWBrhqpH.jpg",
      release_date: "2015-05-08",
      title: "Brad Williams: Fun Size",
      video: false,
      vote_average: 7.5,
      vote_count: 8,
    },
    {
      adult: false,
      gender: 2,
      id: 37722,
      known_for: [
        {
          adult: false,
          backdrop_path: "/kJaisj9uNIzjHum6XM9HD9yI8vu.jpg",
          genre_ids: [36, 10752, 18, 12],
          id: 967,
          media_type: "movie",
          original_language: "en",
          original_title: "Spartacus",
          overview:
            "The rebellious Thracian Spartacus, born and raised a slave, is sold to Gladiator trainer Batiatus. After weeks of being trained to kill for the arena, Spartacus turns on his owners and leads the other slaves in rebellion. As the rebels move from town to town, their numbers swell as escaped slaves join their ranks. Under the leadership of Spartacus, they make their way to southern Italy, where they will cross the sea and return to their homes.",
          poster_path: "/prdCmV8GkDLpguwoxBQczFAwvci.jpg",
          release_date: "1960-10-13",
          title: "Spartacus",
          video: false,
          vote_average: 7.6,
          vote_count: 1673,
        },
        {
          backdrop_path: "/ldtJ6vUo8heez1HVD91Flpg7F5W.jpg",
          first_air_date: "1977-11-04",
          genre_ids: [10759, 18, 10765],
          id: 648,
          media_type: "tv",
          name: "The Incredible Hulk",
          origin_country: ["US"],
          original_language: "en",
          original_name: "The Incredible Hulk",
          overview:
            "During an experiment gone bad, radiation turns a scientist into a raging green behemoth whenever he becomes agitated. Unable to control his transformations, David Banner searches for a cure as he crosses the country, fugitive-style, with a dogged tabloid reporter on his trail.",
          poster_path: "/8q7uFuNuMWTWfcpnCpBuZa3KZXx.jpg",
          vote_average: 7.3,
          vote_count: 350,
        },
        {
          adult: false,
          backdrop_path: "/lEf9WXUppQU3oRnkGyTAcm0TgJz.jpg",
          genre_ids: [28, 12, 14],
          id: 26452,
          media_type: "movie",
          original_language: "en",
          original_title: "Hercules",
          overview:
            "Hercules, a semi-divine being, squares off against King Minos, who is attempting to use science to gain power and take over the world. With the help of a benevolent sorceress, Circe, Hercules tries to save his beloved Cassiopeia from being sacrificed by Minos, and struggles against laser-breathing creatures and an evil sorceress.",
          poster_path: "/9ZxYEH3kM2Tcq8zgPlmuvbAmHwa.jpg",
          release_date: "1983-08-12",
          title: "Hercules",
          video: false,
          vote_average: 4.9,
          vote_count: 75,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Harris",
      popularity: 6.711,
      profile_path: "/RAd9768B0BoUKauL6VgrGiiOIk.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 69614,
      known_for: [
        {
          adult: false,
          backdrop_path: "/s8ftvFvafWWEhApISamHx32bx6h.jpg",
          genre_ids: [12, 28, 878],
          id: 36658,
          media_type: "movie",
          original_language: "en",
          original_title: "X2",
          overview:
            "Professor Charles Xavier and his team of genetically gifted superheroes face a rising tide of anti-mutant sentiment led by Col. William Stryker. Storm, Wolverine and Jean Grey must join their usual nemeses—Magneto and Mystique—to unhinge Stryker's scheme to exterminate all mutants.",
          poster_path: "/tRDvoi7z7B6YdzoRcRQ8LwLA47q.jpg",
          release_date: "2003-04-27",
          title: "X2",
          video: false,
          vote_average: 7,
          vote_count: 8650,
        },
        {
          backdrop_path: "/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
          first_air_date: "2005-09-13",
          genre_ids: [18, 9648, 10765],
          id: 1622,
          media_type: "tv",
          name: "Supernatural",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Supernatural",
          overview:
            "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
          poster_path: "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
          vote_average: 8.3,
          vote_count: 5978,
        },
        {
          backdrop_path: "/vNnLAKmoczRlNarxyGrrw0KSOeX.jpg",
          first_air_date: "2012-10-10",
          genre_ids: [80, 18, 9648, 10759],
          id: 1412,
          media_type: "tv",
          name: "Arrow",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Arrow",
          overview:
            "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
          poster_path: "/gKG5QGz5Ngf8fgWpBsWtlg5L2SF.jpg",
          vote_average: 6.7,
          vote_count: 5056,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Loree",
      popularity: 6.259,
      profile_path: "/jn2QDZPKz49gk8LtBXF1S8EnQd1.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 15376,
      known_for: [
        {
          adult: false,
          backdrop_path: "/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg",
          genre_ids: [27, 53],
          id: 381288,
          media_type: "movie",
          original_language: "en",
          original_title: "Split",
          overview:
            "Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.",
          poster_path: "/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg",
          release_date: "2016-11-15",
          title: "Split",
          video: false,
          vote_average: 7.3,
          vote_count: 15044,
        },
        {
          adult: false,
          backdrop_path: "/ig7qUy7drkEFZNCK7gi0hMn1WMN.jpg",
          genre_ids: [28, 878, 12],
          id: 68726,
          media_type: "movie",
          original_language: "en",
          original_title: "Pacific Rim",
          overview:
            "As war between humankind and monstrous sea creatures wages on, a former pilot and a trainee are paired up to drive a seemingly obsolete special weapon in a desperate effort to save the world.",
          poster_path: "/mmznhaQDwlHWpUwKuNxtQiubbmM.jpg",
          release_date: "2013-07-11",
          title: "Pacific Rim",
          video: false,
          vote_average: 6.8,
          vote_count: 10609,
        },
        {
          adult: false,
          backdrop_path: "/kdbLf3aTQsEXqYlH9vA4fzmnSFz.jpg",
          genre_ids: [10752, 18, 28],
          id: 228150,
          media_type: "movie",
          original_language: "en",
          original_title: "Fury",
          overview:
            "In the last months of World War II, as the Allies make their final push in the European theatre, a battle-hardened U.S. Army sergeant named 'Wardaddy' commands a Sherman tank called 'Fury' and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
          poster_path: "/c5dOrzJiW3jA3Erej6zOgJX8y76.jpg",
          release_date: "2014-10-15",
          title: "Fury",
          video: false,
          vote_average: 7.5,
          vote_count: 10005,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad William Henke",
      popularity: 9.589,
      profile_path: "/6VedPxFRbFblXeWMAkIvURmPEZM.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 51214,
      known_for: [
        {
          adult: false,
          backdrop_path: "/w2rWEjAMYErpNfoK2Z0GFh1LFhN.jpg",
          genre_ids: [80, 18, 53],
          id: 819,
          media_type: "movie",
          original_language: "en",
          original_title: "Sleepers",
          overview:
            "Two gangsters seek revenge on the state jail worker who during their stay at a youth prison sexually abused them. A sensational court hearing takes place to charge him for the crimes.",
          poster_path: "/yUpiEk2EojS9ZEXb3nIQonQCYYF.jpg",
          release_date: "1996-10-18",
          title: "Sleepers",
          video: false,
          vote_average: 7.6,
          vote_count: 2787,
        },
        {
          adult: false,
          backdrop_path: "/xMQBBxvTZLtAqpmGD6o314xkuzC.jpg",
          genre_ids: [53, 9648, 18],
          id: 9667,
          media_type: "movie",
          original_language: "en",
          original_title: "The Jacket",
          overview:
            "A military veteran goes on a journey into the future, where he can foresee his death and is left with questions that could save his life and those he loves.",
          poster_path: "/rubXTfC67U6FrnNl14QNOElef2E.jpg",
          release_date: "2005-03-04",
          title: "The Jacket",
          video: false,
          vote_average: 6.9,
          vote_count: 1190,
        },
        {
          adult: false,
          backdrop_path: "/o7zvlk0HCxRf13Im9ZpZ4okHehr.jpg",
          genre_ids: [35, 18],
          id: 1548,
          media_type: "movie",
          original_language: "en",
          original_title: "Ghost World",
          overview:
            "Two quirky, cynical teenaged girls try to figure out what to do with their lives after high school graduation. After they play a prank on an eccentric, middle aged record collector, one of them befriends him, which causes a rift in the girls' friendship.",
          poster_path: "/uwKqnUPE4dSM0kKuMW0vXpURh2T.jpg",
          release_date: "2001-07-20",
          title: "Ghost World",
          video: false,
          vote_average: 7.1,
          vote_count: 1104,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Renfro",
      popularity: 7.39,
      profile_path: "/s1K2iV3aMckZQ5EU9ovrEk4kSXf.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 1126405,
      known_for: [
        {
          adult: false,
          backdrop_path: "/3uM41OT0RfBkE6Gb6U89LEskJBr.jpg",
          genre_ids: [37, 18, 12],
          id: 281957,
          media_type: "movie",
          original_language: "en",
          original_title: "The Revenant",
          overview:
            "In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.",
          poster_path: "/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
          release_date: "2015-12-25",
          title: "The Revenant",
          video: false,
          vote_average: 7.5,
          vote_count: 15868,
        },
        {
          backdrop_path: "/hiK4qc0tZijQ9KNUnBIS1k4tdMJ.jpg",
          first_air_date: "2004-11-16",
          genre_ids: [18, 9648],
          id: 1408,
          media_type: "tv",
          name: "House",
          origin_country: ["US"],
          original_language: "en",
          original_name: "House",
          overview:
            "Dr. Gregory House, a drug-addicted, unconventional, misanthropic medical genius, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital in New Jersey.",
          poster_path: "/lkvhReTBZ2Ksl0Dl5Oplsf6UYkF.jpg",
          vote_average: 8.6,
          vote_count: 4645,
        },
        {
          backdrop_path: "/fIKc2cR1GglarzChMAb4BOP1qHP.jpg",
          first_air_date: "2006-10-01",
          genre_ids: [80, 18, 9648],
          id: 1405,
          media_type: "tv",
          name: "Dexter",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Dexter",
          overview:
            "Dexter Morgan, a blood spatter pattern analyst for the Miami Metro Police also leads a secret life as a serial killer, hunting down criminals who have slipped through the cracks of justice.",
          poster_path: "/58H6Ctze1nnpS0s9vPmAAzPcipR.jpg",
          vote_average: 8.2,
          vote_count: 2991,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Carter",
      popularity: 5.375,
      profile_path: "/xdQINDoQK3nx5ndIJnYU3qKRM4Y.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 1139648,
      known_for: [
        {
          adult: false,
          backdrop_path: "/59CCw4EtiahW0E5cfTrvdbqPQTo.jpg",
          genre_ids: [16, 35, 10751, 10402],
          id: 335797,
          media_type: "movie",
          original_language: "en",
          original_title: "Sing",
          overview:
            "A koala named Buster recruits his best friend to help him drum up business for his theater by hosting a singing competition.",
          poster_path: "/zZTlF2eVVUkbdmccd3bNUU9T9sD.jpg",
          release_date: "2016-11-23",
          title: "Sing",
          video: false,
          vote_average: 7.1,
          vote_count: 6808,
        },
        {
          adult: false,
          backdrop_path: "/nj84vpuUWdbmYktBzjiWn5Ny1ZF.jpg",
          genre_ids: [18, 36],
          id: 525661,
          media_type: "movie",
          original_language: "en",
          original_title: "Bombshell",
          overview:
            "Bombshell is a revealing look inside the most powerful and controversial media empire of all time; and the explosive story of the women who brought down the infamous man who created it.",
          poster_path: "/gbPfvwBqbiHpQkYZQvVwB6MVauV.jpg",
          release_date: "2019-12-13",
          title: "Bombshell",
          video: false,
          vote_average: 6.8,
          vote_count: 2431,
        },
        {
          adult: false,
          backdrop_path: "/vNpuAxGTl9HsUbHqam3E9CzqCvX.jpg",
          first_air_date: "2005-03-24",
          genre_ids: [35],
          id: 2316,
          media_type: "tv",
          name: "The Office",
          origin_country: ["US"],
          original_language: "en",
          original_name: "The Office",
          overview:
            "The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.",
          poster_path: "/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
          vote_average: 8.6,
          vote_count: 2424,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Morris",
      popularity: 5.692,
      profile_path: "/m4Hp7SzAel4eOQUQDILlxHMzSeZ.jpg",
    },
    {
      adult: false,
      gender: 2,
      id: 1256726,
      known_for: [
        {
          adult: false,
          backdrop_path: "/6G2fLCVm9fiLyHvBrccq6GSe2ih.jpg",
          genre_ids: [28, 12, 14, 878],
          id: 284053,
          media_type: "movie",
          original_language: "en",
          original_title: "Thor: Ragnarok",
          overview:
            "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
          poster_path: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
          release_date: "2017-10-24",
          title: "Thor: Ragnarok",
          video: false,
          vote_average: 7.6,
          vote_count: 17787,
        },
        {
          adult: false,
          backdrop_path: "/a7sAqMKv5tkAdMzFfIhPqIBmQ9g.jpg",
          genre_ids: [878, 28, 12],
          id: 102899,
          media_type: "movie",
          original_language: "en",
          original_title: "Ant-Man",
          overview:
            "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
          poster_path: "/rS97hUJ1otKTTripGwQ0ujbuIri.jpg",
          release_date: "2015-07-14",
          title: "Ant-Man",
          video: false,
          vote_average: 7.1,
          vote_count: 17182,
        },
        {
          adult: false,
          backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
          genre_ids: [28, 12, 878],
          id: 497698,
          media_type: "movie",
          original_language: "en",
          original_title: "Black Widow",
          overview:
            "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
          poster_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
          release_date: "2021-07-07",
          title: "Black Widow",
          video: false,
          vote_average: 7.4,
          vote_count: 7736,
        },
      ],
      known_for_department: "Production",
      media_type: "person",
      name: "Brad Winderbaum",
      popularity: 5.641,
      profile_path: null,
    },
    {
      adult: false,
      gender: 2,
      id: 92024,
      known_for: [
        {
          adult: false,
          backdrop_path: "/zQ4sKBzuX3tgGpl6eiGYT0ur9Nk.jpg",
          genre_ids: [18, 10749],
          id: 24584,
          media_type: "movie",
          original_language: "en",
          original_title: "Get Real",
          overview:
            "Steven spends his school days longing for all-star athlete John. But John has a gorgeous girlfriend, and Steven is still in the closet about being gay. The only one who knows the teenager's secret is his friend Linda. After a curious run-in with John in a public restroom, Steven starts to wonder if the jock is straight after all. When they start a romance, it threatens to expose the truth about both of them.",
          poster_path: "/k7KCBnt1VXFhPjoTSt4MePr1MpI.jpg",
          release_date: "1998-08-16",
          title: "Get Real",
          video: false,
          vote_average: 6.9,
          vote_count: 123,
        },
        {
          backdrop_path: "/5HjfWdjRHawvIrbg4pP3Oj6N9u2.jpg",
          first_air_date: "2000-03-27",
          genre_ids: [10766, 18],
          id: 5080,
          media_type: "tv",
          name: "Doctors",
          origin_country: ["GB"],
          original_language: "en",
          original_name: "Doctors",
          overview:
            "Set in the fictional Midlands town of Letherbridge, defined as being close to the city of Birmingham, this soap opera follows the staff and families of a doctor's surgery.",
          poster_path: "/thZKqMWevSJVTeAiedy40umvz11.jpg",
          vote_average: 4.7,
          vote_count: 29,
        },
        {
          backdrop_path: "/qMTjNRKm2GgsUlaKSRkqpXCwrqc.jpg",
          first_air_date: "2002-01-08",
          genre_ids: [18],
          id: 772,
          media_type: "tv",
          name: "Footballers' Wives",
          origin_country: ["GB"],
          original_language: "en",
          original_name: "Footballers' Wives",
          overview:
            "Footballers' Wives is a British television drama surrounding the fictional Premier League Association football club Earls Park F.C., its players, and their wives. It was broadcast on the ITV network from 8 January 2002 to 14 April 2006. The show began with a multi-lateral focus on a variety of different types of relationships explored; however, from the third series onward, the primary focus was on a complex love triangle between Tanya Turner, Amber Gates and Conrad Gates.",
          poster_path: "/xWlLridFURu88WeII6Pe1BCRgYS.jpg",
          vote_average: 5.8,
          vote_count: 8,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Gorton",
      popularity: 5.063,
      profile_path: "/ftiOBFsfsF3CiJQQL7FzU3mwuPp.jpg",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 399810,
      media_type: "movie",
      original_language: "en",
      original_title: "Brad Williams: Daddy Issues",
      overview:
        "In this hilarious new comedy special, stand-up Brad Williams tackles race and political correctness, as well as how his father raised him to deal with adversity.",
      popularity: 1.732,
      poster_path: "/tsI1mSNBRvYDcx8q2ONV2e6xaAS.jpg",
      release_date: "2016-05-20",
      title: "Brad Williams: Daddy Issues",
      video: false,
      vote_average: 7,
      vote_count: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 576216,
      known_for: [
        {
          adult: false,
          backdrop_path: "/iAmTmSUzpxrxz1KJwhrXsdMFRfi.jpg",
          genre_ids: [27, 35],
          id: 75761,
          media_type: "movie",
          original_language: "en",
          original_title: "John Dies at the End",
          overview:
            "A new drug promises out-of-body experiences, but users are coming back changed forever, and an otherworldly invasion of Earth is underway.",
          poster_path: "/1IsviP0Tb05xUAFWz5b7FJ0qIHP.jpg",
          release_date: "2013-01-25",
          title: "John Dies at the End",
          video: false,
          vote_average: 6.4,
          vote_count: 528,
        },
        {
          adult: false,
          backdrop_path: "/bltNf2ajBm3wkfiF5Lglw7DS0vk.jpg",
          first_air_date: "2021-03-12",
          genre_ids: [99],
          id: 118924,
          media_type: "tv",
          name: "Marvel Studios: Assembled",
          origin_country: ["US"],
          original_language: "en",
          original_name: "Marvel Studios: Assembled",
          overview:
            "Go behind the scenes of the shows and movies of the Marvel Cinematic Universe, following the filmmakers, cast and crew, and Marvel heroes every step of the way.",
          poster_path: "/v2BHRwtQVkt5fssLdo5MpFgHJPY.jpg",
          vote_average: 7.4,
          vote_count: 150,
        },
        {
          adult: false,
          backdrop_path: "/czHz1DWWE0bcffXybT7u1wNshSx.jpg",
          genre_ids: [10770, 99],
          id: 259910,
          media_type: "movie",
          original_language: "en",
          original_title: "Marvel Studios: Assembling a Universe",
          overview:
            'A look at the story behind Marvel Studios and the Marvel Cinematic Universe, featuring interviews and behind-the-scenes footage from all of the Marvel films, the Marvel One-Shots and "Marvel\'s Agents of S.H.I.E.L.D."',
          poster_path: "/41Ke02UzYoPsiTc3YbomPGiQKMl.jpg",
          release_date: "2014-03-18",
          title: "Marvel Studios: Assembling a Universe",
          video: false,
          vote_average: 7.1,
          vote_count: 125,
        },
      ],
      known_for_department: "Production",
      media_type: "person",
      name: "Brad Baruh",
      popularity: 4.501,
      profile_path: null,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 84267,
      media_type: "movie",
      original_language: "en",
      original_title: "Colin & Brad: Two Man Group",
      overview:
        "Colin Mochrie and Brad Sherwood, stars of the Emmy®-winning Whose Line Is It Anyway?, have finally recorded their hilarious live stage show!! These masters of improv comedy have performed their outrageous, one-of-a-kind show to sold out audiences all over the country. Colin and Brad’s TWO MAN GROUP is a riotously funny, interactive, and completely improvised tour de force. Using nothing but their lightning fast wits and some audience volunteers, Colin and Brad create pandemonium on the spot in one of the funniest live shows you will ever see.",
      popularity: 1.2,
      poster_path: null,
      release_date: "2011-03-08",
      title: "Colin & Brad: Two Man Group",
      video: false,
      vote_average: 7.4,
      vote_count: 10,
    },
    {
      adult: false,
      gender: 2,
      id: 228428,
      known_for: [
        {
          adult: false,
          backdrop_path: "/5OeY4U2rzePxWq2rkqMajUx2gz7.jpg",
          genre_ids: [16, 10751, 12, 14, 10749],
          id: 812,
          media_type: "movie",
          original_language: "en",
          original_title: "Aladdin",
          overview:
            "Princess Jasmine grows tired of being forced to remain in the palace, so she sneaks out into the marketplace, in disguise, where she meets street-urchin Aladdin.  The couple falls in love, although Jasmine may only marry a prince.  After being thrown in jail, Aladdin becomes embroiled in a plot to find a mysterious lamp, with which the evil Jafar hopes to rule the land.",
          poster_path: "/w4RWEwVp3d9MQs3MAy2Yv7XWUez.jpg",
          release_date: "1992-11-25",
          title: "Aladdin",
          video: false,
          vote_average: 7.6,
          vote_count: 9703,
        },
        {
          adult: false,
          backdrop_path: "/7PR2yMwXuXelAcp3qpJ3isZCdd0.jpg",
          genre_ids: [12, 28, 53, 878],
          id: 563,
          media_type: "movie",
          original_language: "en",
          original_title: "Starship Troopers",
          overview:
            'Set in the future, the story follows a young soldier named Johnny Rico and his exploits in the Mobile Infantry. Rico\'s military career progresses from recruit to non-commissioned officer and finally to officer against the backdrop of an interstellar war between mankind and an arachnoid species known as "the Bugs".',
          poster_path: "/cxCmv23O7p3hyHwqoktHYkZcGsY.jpg",
          release_date: "1997-11-07",
          title: "Starship Troopers",
          video: false,
          vote_average: 7,
          vote_count: 3824,
        },
        {
          adult: false,
          backdrop_path: "/mOOJm3tamy9iHg2mOEA77CM6ufZ.jpg",
          genre_ids: [10751, 12, 16, 10749],
          id: 15969,
          media_type: "movie",
          original_language: "en",
          original_title: "The Return of Jafar",
          overview:
            "The evil Jafar escapes from the magic lamp as an all-powerful genie, ready to plot his revenge against Aladdin. From battling elusive villains atop winged horses, to dodging flames inside an exploding lava pit, it's up to Aladdin - with Princess Jasmine and the outrageously funny Genie by his side - to save the kingdom once and for all.",
          poster_path: "/7SC793qtORB6YL4mu0F5o3hfjDQ.jpg",
          release_date: "1994-05-20",
          title: "The Return of Jafar",
          video: false,
          vote_average: 6.1,
          vote_count: 2579,
        },
      ],
      known_for_department: "Acting",
      media_type: "person",
      name: "Brad Kane",
      popularity: 3.563,
      profile_path: null,
    },
  ],
};
